[programs.devnet]
contract_a = "Bqo8fvsrNRfxm3GPcAFqHCzJe2JQB6m5MFyxdaHwin1Z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/serhiistanislav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
